# Configuration for probot-no-response - https://github.com/lee-dohm/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 3
# Label requiring a response
responseRequiredLabel: waiting-for-requestor
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because the requestor didn't provide any additional comment.
